{
	"version": 1613938928,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/playbutton-sheet0.png",
		"images/gametitle-sheet0.png",
		"images/bg-sheet0.png",
		"images/frame-sheet0.png",
		"images/images-sheet0.png",
		"images/images-sheet1.png",
		"images/mute-sheet0.png",
		"images/mute-sheet1.png",
		"images/sprite-sheet0.png",
		"images/voltar-sheet0.png",
		"images/brush-sheet0.png",
		"images/brushcolor-sheet0.png",
		"images/brushcolor-sheet1.png",
		"images/brush_local-sheet0.png",
		"images/brushsize-sheet0.png",
		"images/brush_size_local-sheet0.png",
		"images/cam-sheet0.png",
		"images/objects-sheet0.png",
		"images/objects-sheet1.png",
		"images/color_size-sheet0.png",
		"images/paint-sheet0.png",
		"images/frame2-sheet0.png",
		"images/pincel-sheet0.png",
		"images/mouseposition-sheet0.png",
		"images/select_level_title-sheet0.png",
		"images/eraser-sheet0.png",
		"images/restry-sheet0.png",
		"images/black_screen-sheet0.png",
		"images/lv-sheet0.png",
		"images/moregames-sheet0.png",
		"images/sprite4-sheet0.png",
		"media/cloud click.m4a",
		"media/cloud click.ogg",
		"media/droplet_06 - parede.ogg",
		"media/camera-click.m4a",
		"media/camera-click.ogg",
		"media/petersburger.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}